export const GET_PROCESSOS = "GET_PROCESSOS";

export const LOGIN_ESCAVADOR_SUCCESS = "LOGIN_ESCAVADOR_SUCCESS";
export const LOGIN_ESCAVADOR_WAITING = "LOGIN_ESCAVADOR_WAITING"
export const LOGIN_ESCAVADOR_FAILURE = "LOGIN_ESCAVADOR_FAILURE";;