export const GET_USERS = "GET_USERS";

export const LOGIN_ESCAVADOR_SUCCESS = "LOGIN_ESCAVADOR_SUCCESS";
export const LOGIN_ESCAVADOR_WAITING = "LOGIN_ESCAVADOR_WAITING"
export const LOGIN_ESCAVADOR_FAILURE = "LOGIN_ESCAVADOR_FAILURE";;