export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const GET_LOGGED_USER = "GET_LOGGED_USER";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_WAITING = "LOGIN_WAITING"
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_WAITING = "REGISTER_WAITING"
export const REGISTER_FAILURE = "REGISTER_FAILURE";